#!/usr/bin/env python3
"""
MahiCyber Email Checker
GitHub: mahi-cyberaware
Tool made by Mahi
Uses holehe to check email registrations and data leaks.
"""

import sys
import os
import csv
import json
import subprocess
import tempfile
import glob
from datetime import datetime
from colorama import init, Fore, Style

init(autoreset=True)

# ========== BANNER ==========
def show_banner():
    banner = f"""
{Fore.RED}╔══════════════════════════════════════════════════════════╗{Style.RESET_ALL}
{Fore.RED}║{Fore.CYAN}    ███╗   ███╗ █████╗ ██╗  ██╗██╗{Fore.YELLOW}     ██████╗██╗   ██╗██████╗ ███████╗██████╗ {Fore.RED}║{Style.RESET_ALL}
{Fore.RED}║{Fore.CYAN}    ████╗ ████║██╔══██╗██║  ██║██║{Fore.YELLOW}    ██╔════╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗{Fore.RED}║{Style.RESET_ALL}
{Fore.RED}║{Fore.CYAN}    ██╔████╔██║███████║███████║██║{Fore.YELLOW}    ██║      ╚████╔╝ ██████╔╝█████╗  ██████╔╝{Fore.RED}║{Style.RESET_ALL}
{Fore.RED}║{Fore.CYAN}    ██║╚██╔╝██║██╔══██║██╔══██║██║{Fore.YELLOW}    ██║       ╚██╔╝  ██╔══██╗██╔══╝  ██╔══██╗{Fore.RED}║{Style.RESET_ALL}
{Fore.RED}║{Fore.CYAN}    ██║ ╚═╝ ██║██║  ██║██║  ██║██║{Fore.YELLOW}    ╚██████╗   ██║   ██████╔╝███████╗██║  ██║{Fore.RED}║{Style.RESET_ALL}
{Fore.RED}║{Fore.CYAN}    ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝{Fore.YELLOW}     ╚═════╝   ╚═╝   ╚═════╝ ╚══════╝╚═╝  ╚═╝{Fore.RED}║{Style.RESET_ALL}
{Fore.RED}╠══════════════════════════════════════════════════════════╣{Style.RESET_ALL}
{Fore.RED}║{Fore.GREEN}               MahiCyber Email Checker                     {Fore.RED}║{Style.RESET_ALL}
{Fore.RED}║{Fore.YELLOW}           GitHub: mahi-cyberaware                         {Fore.RED}║{Style.RESET_ALL}
{Fore.RED}║{Fore.CYAN}                 Tool made by Mahi                           {Fore.RED}║{Style.RESET_ALL}
{Fore.RED}╚══════════════════════════════════════════════════════════╝{Style.RESET_ALL}
"""
    print(banner)

# ---------- Helper Functions ----------
def ensure_records_folder():
    if not os.path.exists("records"):
        os.makedirs("records")
        print(f"{Fore.CYAN}Created 'records' folder for result files.")

def check_holehe_installed():
    try:
        subprocess.run(["holehe", "--help"], capture_output=True, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False

def run_holehe(email):
    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            result = subprocess.run(
                ["holehe", email, "--csv"],
                cwd=tmpdir,
                capture_output=True,
                text=True,
                timeout=90
            )
        except subprocess.TimeoutExpired:
            print(f"{Fore.RED}Holehe timed out after 90 seconds.")
            return None
        except Exception as e:
            print(f"{Fore.RED}Unexpected subprocess error: {e}")
            return None

        csv_files = glob.glob(os.path.join(tmpdir, "*.csv"))
        if not csv_files:
            print(f"{Fore.RED}No CSV file generated by holehe.")
            return None

        csv_path = max(csv_files, key=os.path.getctime)

        sites = []
        try:
            with open(csv_path, 'r', newline='', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    site_name = row.get('name', 'Unknown')
                    exists_raw = row.get('exists', '').strip().lower()
                    if exists_raw in ['true', '1', 'yes']:
                        status = 'registered'
                    elif exists_raw in ['false', '0', 'no']:
                        status = 'not registered'
                    else:
                        status = 'unknown'
                    sites.append({"name": site_name, "status": status})
        except Exception as e:
            print(f"{Fore.RED}Error parsing CSV: {e}")
            return None

        breaches = []
        for line in result.stdout.split('\n'):
            if 'breach' in line.lower() or 'leak' in line.lower():
                breaches.append({"name": line.strip(), "date": "Unknown"})

        return {"sites": sites, "breaches": breaches}

def display_results(data, email):
    if not data:
        print(f"{Fore.RED}No data to display.")
        return

    print(f"\n{Fore.CYAN}=== Results for {email} ===\n")

    sites = data.get("sites", [])
    registered = [s["name"] for s in sites if s["status"] == "registered"]
    not_registered = [s["name"] for s in sites if s["status"] == "not registered"]
    unknown = [s["name"] for s in sites if s["status"] == "unknown"]

    if registered:
        print(f"{Fore.GREEN}REGISTERED ({len(registered)}):")
        for site in registered:
            print(f"  {Fore.GREEN}✓ {site}")
    if not_registered:
        print(f"\n{Fore.BLUE}NOT REGISTERED ({len(not_registered)}):")
        for site in not_registered:
            print(f"  {Fore.BLUE}✗ {site}")
    if unknown:
        print(f"\n{Fore.MAGENTA}UNKNOWN ({len(unknown)}):")
        for site in unknown:
            print(f"  {Fore.MAGENTA}? {site}")

    breaches = data.get("breaches", [])
    if breaches:
        print(f"\n{Fore.RED}Data Breaches Found:")
        for breach in breaches:
            print(f"  {Fore.RED}• {breach.get('name', 'Unknown')}")
    else:
        print(f"\n{Fore.GREEN}No data leaks found for this email.")

def save_results(data, email):
    ensure_records_folder()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_email = email.replace('@', '_').replace('.', '_')
    filename = f"records/result_{safe_email}_{timestamp}.json"
    with open(filename, "w") as f:
        json.dump(data, f, indent=2)
    print(f"\n{Fore.CYAN}Full results saved to {filename}")

def main():
    show_banner()
    if len(sys.argv) != 2:
        print("Usage: python3 checker.py <email>")
        sys.exit(1)
    email = sys.argv[1].strip().lower()

    if not check_holehe_installed():
        print(f"{Fore.RED}Error: holehe is not installed or not in PATH.")
        print(f"{Fore.YELLOW}Please install it using:")
        print("  sudo apt install holehe   (Kali/Ubuntu)")
        print("  or")
        print("  pipx install holehe        (recommended for virtual env)")
        sys.exit(1)

    print(f"{Fore.CYAN}Running holehe on {email} ...")
    data = run_holehe(email)
    if data:
        display_results(data, email)
        save_results(data, email)
    else:
        print(f"{Fore.RED}Failed to retrieve data from holehe.")

if __name__ == "__main__":
    main()
